# Generated by Django 4.0 on 2022-01-06 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytypes',
            old_name='catergory',
            new_name='category',
        ),
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ImageField(upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание работы')),
                ('status', models.CharField(choices=[('Drf', 'Черновик'), ('Pub', 'Опубликовано'), ('Del', 'Удалено')], default='Pub', max_length=3)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.categorytypes', verbose_name='Категория')),
            ],
        ),
    ]
