# Generated by Django 4.0 on 2022-01-06 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_catergory_categorytypes_category_artworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworks',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата обновления'),
        ),
    ]
