# Generated by Django 4.0 on 2022-01-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_artworks_date_create_artworks_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='artwork',
            field=models.ImageField(upload_to='artworks/'),
        ),
    ]
