# Generated by Django 4.0 on 2022-01-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_artworks_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='artworks',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
