# Generated by Django 4.0 on 2022-01-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_artworks_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
